# Redirect any URLs with the language code in them already
[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 301
  force = true

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Redirect for end-userâ€™s browser preference override
[[redirects]]
  from = "/*"
  to = "/pt/:splat"
  status = 302
  conditions = {Language = ["pt"]}

# Default
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
